steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/cotproject1-436018/image-upload-app', '.']

  # Step 2: Run automated tests using pytest with Python 3.10
  - name: 'python:3.10-slim'  # Use Python 3.10 for compatibility with google-generativeai
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install --upgrade pip
        pip install -r requirements.txt
        pytest tests/  # Run tests from the tests directory

  # Step 3: Push the Docker image to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/cotproject1-436018/image-upload-app']

  # Step 4: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'image-upload-app' # This should be your Cloud Run service name
      - '--image'
      - 'gcr.io/cotproject1-436018/image-upload-app'
      - '--region'
      - 'us-central1' # Replace with your preferred region
      - '--platform'
      - 'managed' 
      - '--allow-unauthenticated'

# Set build options
options:
  logging: CLOUD_LOGGING_ONLY

# Define the service account that Cloud Build will use to deploy
serviceAccount: image-upload-app-sa@cotproject1-436018.iam.gserviceaccount.com
